trigger: none  # No se ejecuta automáticamente, solo manualmente o tras otros pipelines

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: frontend
      source: 'ESI-MEDIA'  # Nombre del proyecto
      pipeline: 'FE Compilation'  # Nombre del pipeline de frontend
      trigger:
        branches:
          include:
            - develop
    - pipeline: backend
      source: 'ESI-MEDIA'  # Nombre del proyecto
      pipeline: 'BE Compilation'  # Nombre del pipeline de backend
      trigger:
        branches:
          include:
            - develop

variables:
  dockerRegistryServiceConnection: 'docker-hub-connection'  # Nombre de tu service connection
  imageRepository: 'esimedia'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
  - stage: BuildDocker
    displayName: 'Build and Push Docker Image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - job: DockerBuild
        displayName: 'Build Docker Image'
        steps:
          - checkout: self
            displayName: 'Checkout Source Code'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              Dockerfile: $(dockerfilePath)
              repository: $(imageRepository)
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: 'Push Docker Image to Registry'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              command: 'push'
              tags: |
                $(tag)
                latest

          - script: |
              echo "Docker image built and pushed successfully!"
              echo "Image: $(imageRepository):$(tag)"
              echo "Image: $(imageRepository):latest"
            displayName: 'Display Build Info'
